### ISSUE TITLE
Expand!!!111oneoneone

### ISSUE THREAD

**Issue by fabiankrol** [aerosol/fotd#1]
### `Elixir Module of the Week`

**Comment by fabiankrol** [comment]
# 🤔

**Comment by aerosol** [comment]
Hi Fabian, thanks for stopping by :) Would you care to elaborate? Not sure if serious.

**Comment by fabiankrol** [comment]
Hey! Indeed i was half joking ;) 
I seriously thing reading up on a random module might be beneficiary as well. 
I guess [IN PROGRESS: proper hexdocs links whenever possible](https://github.com/aerosol/fotd/commit/1b3c8d2f15cfc52eaacb36a4e770647b5bd55ceb#diff-04c6e90faac2675aa89e2176d2eec7d8R8) might just do the trick

**Comment by fabiankrol** [comment]
BTW Do you fancy for contributors?

**Comment by aerosol** [comment]
Of course!

**Comment by aerosol** [comment]
Module docs are straight forward to include, but I would need to get yet another domain :sob:
 
There's https://pymotw.com BTW, but it's manually curated.
