### ISSUE TITLE
Don't show functions from private modules

### ISSUE THREAD

**Issue by wojtekmach** [aerosol/fotd#4]
Even though the function is documented, if module has `@moduledoc false` it's considered private API:

- https://github.com/elixir-lang/elixir/blob/v1.7.0/lib/mix/lib/mix/local.ex#L2
- https://hexdocs.pm/mix/Mix.Local.html#archives_tasks/0 404s

<img width="949" alt="screenshot 2018-11-09 at 08 42 23" src="https://user-images.githubusercontent.com/76071/48249423-65433580-e3fb-11e8-8667-ba8a5fca160d.png">

**Comment by aerosol** [comment]
Aaaand it's live :sweat_smile:  Thanks!
